// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAziA2YD0W4sWhk2ZizSkyj4dUZ9SU5E8k',
    appId: '1:368011583682:web:682a6503ee335f5f1e5b5b',
    messagingSenderId: '368011583682',
    projectId: 'cris-lost-and-found',
    authDomain: 'cris-lost-and-found.firebaseapp.com',
    storageBucket: 'cris-lost-and-found.firebasestorage.app',
    measurementId: 'G-YVBN8SSER7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxvKanWvSLvbUvQqGCw7Mxv_ZYHeRDzY',
    appId: '1:368011583682:android:e2c01944a24e0f501e5b5b',
    messagingSenderId: '368011583682',
    projectId: 'cris-lost-and-found',
    storageBucket: 'cris-lost-and-found.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW4cOwFezCyhgzOnIsmndvcovdSxxjinM',
    appId: '1:368011583682:ios:7444d1e79763725d1e5b5b',
    messagingSenderId: '368011583682',
    projectId: 'cris-lost-and-found',
    storageBucket: 'cris-lost-and-found.firebasestorage.app',
    iosClientId: '368011583682-q0bv9i8f06fl9bgf5rgotjn6qq8rqtl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW4cOwFezCyhgzOnIsmndvcovdSxxjinM',
    appId: '1:368011583682:ios:7444d1e79763725d1e5b5b',
    messagingSenderId: '368011583682',
    projectId: 'cris-lost-and-found',
    storageBucket: 'cris-lost-and-found.firebasestorage.app',
    iosClientId: '368011583682-q0bv9i8f06fl9bgf5rgotjn6qq8rqtl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAziA2YD0W4sWhk2ZizSkyj4dUZ9SU5E8k',
    appId: '1:368011583682:web:0f9b659277e1d8b31e5b5b',
    messagingSenderId: '368011583682',
    projectId: 'cris-lost-and-found',
    authDomain: 'cris-lost-and-found.firebaseapp.com',
    storageBucket: 'cris-lost-and-found.firebasestorage.app',
    measurementId: 'G-VXNBXL95LH',
  );
}
